<a href="https://colab.research.google.com/github/Yotun12/ML/blob/main/%22%D0%9B%D0%B0%D0%B11_2%2C_%D0%9B%D0%BE%D0%B7%D0%B5%D0%BD%D0%BA%D0%BE_%D0%94_%D0%A1_%2C_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_9%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

Завдання 1: Задати вектор, що складається з перших 5 натуральних чисел

In [ ]:
vector=np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

Завдання 2: Транспорування вектора

In [ ]:
v_1=np.matrix([1,2,3,4,5])
print(v_1)
v_2=v_1.T
v_2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

Завдання 3: Напишіть функцію, яка повертає вектор у зворотному порядку

In [ ]:
v=np.array([1,2,3,4,5])
print(v[::-1])

[5 4 3 2 1]


In [ ]:
v=np.flip([1,2,3,4,5])
print(v)

[5 4 3 2 1]


Завдання 4: Обчисліть середнє значення вектор

In [ ]:
print(np.mean(v))

3.0


Задвання 5: Знайти найбільше та найменше значення

In [ ]:
print(np.max(v))
print(np.min(v))

5
1


Завдання 6: Обчислити скалярний добуток (dot.product) двох вектора

In [ ]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

print(np.dot(v1,v2))
print(v1*v2)

32
[ 4 10 18]


Завдання 7: Напишіть функцію, яка нормалізує вектор (зводить до одиничної множини)

In [ ]:
v=np.array([1,2,3,4,5])
norm=np.linalg.norm(v)
print(norm)
v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

Завдання 8: Задати два вектори. Визначет, чи є воно ортогональним.

In [ ]:
v1=np.array([1,0,0])
v2=np.array([0,1,0])
np.dot(v1,v2)



np.int64(0)

Завдання 9: Визначити унікальні елементи вектора

In [ ]:
v=np.array([1,2,3,2,4,5,3])
np.unique(v)

array([1, 2, 3, 4, 5])

Завдання 10: Знайти вектор

In [ ]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1-v2)
print(v2-v1)
print(v1+v2)
print(v2+v1)
print(v1*v2)
print(v2*v1)
print(v1/v2)
print(v2/v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


Завдання 11: Перевірити, чи дорівнює довжина вектор 5

In [ ]:
v=np.array([1,2,3,4,5])
length=np.linalg.norm(v)
np.isclose(length,5)

np.False_

Завдання 12: Задати матрицю заповнену випадковими числами

In [ ]:
a=np.random.randint(0, 11, (3,3))
a

array([[ 8,  9,  2],
       [ 1, 10,  1],
       [ 8, 10,  2]])

Завдання 13: Визначити визначник матриці

In [ ]:
np.linalg.det(a)

np.float64(-5.999999999999992)

Завдання 14: Знаходження оберненої матриці

In [ ]:
np.linalg.inv(a)

array([[-1.66666667e+00, -3.33333333e-01,  1.83333333e+00],
       [-1.00000000e+00, -1.50114662e-16,  1.00000000e+00],
       [ 1.16666667e+01,  1.33333333e+00, -1.18333333e+01]])

Завдання 15: Розв'яжіть систему лінійних рівнянь A*x=b, де A-матриця коефіцієнтів, b-вектор вільних членів

In [ ]:
a=np.array([[1,3,-4],[0,2,-3],[-2,2,5]])
b=np.array([5,3,4])
x=np.linalg.solve(a,b)
print(x)
inv_a=np.linalg.inv(a)
x1=inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


Завдання 16: Множення двох матриць

In [ ]:
a=np.array([[1,3,-4],[0,2,-3],[-2,2,5]])
b=np.array([5,3,4])
np.dot(a,b)


array([-2, -6, 16])

In [ ]:
a=np.matrix([[1,3,-4],[0,2,-3]])
b=np.matrix([[5,3,4],[2,3,5],[3,2,3]])
print(a)
print(b)
print(np.dot(a,b))


[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


Завдання 17: Транспорування матриці

In [ ]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [ ]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


Завдання 18: Перевірка симетричності матриці

In [ ]:
matrix=np.matrix([[2,2,2],[2,2,2],[2,2,2]])
np.allclose(matrix ,matrix.T)

True

Завдання 19: Обчислення сліду матриці

In [ ]:
np.trace(matrix)

np.int64(6)

Завдання 20: Дії з матрицями

In [ ]:
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[5,6],[7,8]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Завдання 21: Піднесення матриці ло ступеня

In [ ]:
a=np.matrix([[1,2],[3,4]])
np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])

Завдання 22: Сортування рядків або стовпців матриці

In [ ]:
b=np.matrix([[5,3,4],[2,3,5],[3,2,3]])
print(b)
print(np.sort(b,axis=0))
print(np.sort(b,axis=1))
print(np.sort(b,axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [ ]:
a=np.matrix([[1,4],[3,1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


Завданн 23: Підрахувати суму елементів кожного рядка матриці. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums=np.sum(a, axis=1).reshape(-1,1)
print("Сума елементів кожного рядка")
print(row_sums)


Сума елементів кожного рядка
[[5]
 [4]]


Висновок: Протягом лабораторної роботи ми продовжили вивчення функцій та можливостей бібліотеки Numpy і як вона може ще взаємодіяти з вектора, і матрицями.  