<a href="https://colab.research.google.com/github/Yotun12/ML/blob/main/%D0%9B%D0%B0%D0%B11%2C_%D0%9B%D0%BE%D0%B7%D0%B5%D0%BD%D0%BA%D0%BE_%D0%94_%D0%A1_%2C_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
np.__version__

'2.0.2'

Завдання 1: Створити матрицю 3*3 та заповнити її натуральними числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3,3) )
matrix


array([[2, 3, 3],
       [4, 1, 4],
       [4, 4, 2]])

Завдання 2: Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(32.0)

Завдання 3: Знайти добуток всіх елементів матриці

In [ ]:
product=np.prod(matrix)
product

np.int64(9216)

In [ ]:
prod_1=np.prod(matrix[0])
prod_2=np.prod(matrix[1])
prod_3=np.prod(matrix[2])
prod_1*prod_2*prod_3


np.int64(9216)

Завдання 4: Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(27)

Завдання 5: Знайти найбільший та найменший елемент матриці

In [ ]:
max_element=np.max(matrix)
print("Найбільший елемент матриці", max_element)
min_element=np.min(matrix)
print("Найменший елемент матриці", min_element)

Найбільший елемент матриці 4
Найменший елемент матриці 1


Завдання 6: Знайти середнє значення матриці

In [ ]:
mean=np.mean(matrix)
print("Середнє значення матриці", mean)

Середнє значення матриці 3.0


Завдання 7: Знайти матрицющо складена з квадратних коренів

In [ ]:
sqrt_m=np.sqrt(matrix)
print("Матриця з квадратних коренів")
print(sqrt_m)

Матриця з квадратних коренів
[[1.41421356 1.73205081 1.73205081]
 [2.         1.         2.        ]
 [2.         2.         1.41421356]]


Завдання 8: Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums=np.sum(matrix, axis=1).reshape(-1,1)
print("Сума елементів кожного рядка")
print(row_sums)

Сума елементів кожного рядка
[[ 8]
 [ 9]
 [10]]


Завдання 9: Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням

In [ ]:
vector=np.random.randint(0,10,size=25)
print("Початковий вектор")
print(vector)
sort_vector=np.sort(vector)[::-1]
print("Вектор відсортований за спаданням")
print(sort_vector)

Початковий вектор
[7 1 5 4 8 0 2 5 8 7 6 2 0 0 9 2 7 7 7 6 3 0 1 8 1]
Вектор відсортований за спаданням
[9 8 8 8 7 7 7 7 7 6 6 5 5 4 3 2 2 2 1 1 1 0 0 0 0]


Завдання 10: Знайти моду, медіану, середнє, максимальне та мінімальне значення

In [ ]:
!pip install scipy

In [ ]:
from scipy import stats

In [ ]:
mode=stats.mode(vector)
median=np.median(vector)
mean=np.mean(vector)
max=np.max(vector)
min=np.min(vector)
print("Мода вектора",mode)
print("Медіана вектора",median)
print("Середнє значення вектора",mean)
print("Максимальне значення вектора",max)
print("Мінімальне значення вектора",min)


Мода вектора ModeResult(mode=np.int64(7), count=np.int64(5))
Медіана вектора 5.0
Середнє значення вектора 4.24
Максимальне значення вектора 9
Мінімальне значення вектора 0


Завдання 11: Створити дві матриці 4*4 та заповнити числами від 1 до 10. Обчислити суму, різницю, поелементний добуток та частку

In [ ]:
matrix_1=np.random.randint(1,11, size=(4,4))
matrix_2=np.random.randint(1,11, size=(4,4))
print("Матриця 1")
print(matrix_1)
print("\nМатриця 2")
print(matrix_2)

Матриця 1
[[ 2  7  4  4]
 [ 7  9  4  9]
 [ 8  4  9  6]
 [10  7  3  2]]

Матриця 2
[[ 3  3  8  7]
 [ 8  6  9  9]
 [ 5 10 10  9]
 [ 2  8  4  6]]


In [ ]:
matrix_sum=matrix_1+matrix_2
matrix_diff=matrix_1-matrix_2
matrix_prod=matrix_1*matrix_2
matrix_divis=np.divide(matrix_1,matrix_2, where=(matrix_2!=0))
print("Сума матриць")
print(matrix_sum)
print("\nРізниця матриць")
print(matrix_diff)
print("\nПоелементний добуток матриць")
print(matrix_prod)
print("\nЧастка матриць")
print(matrix_divis)

Сума матриць
[[ 5 10 12 11]
 [15 15 13 18]
 [13 14 19 15]
 [12 15  7  8]]

Різниця матриць
[[-1  4 -4 -3]
 [-1  3 -5  0]
 [ 3 -6 -1 -3]
 [ 8 -1 -1 -4]]

Поелементний добуток матриць
[[ 6 21 32 28]
 [56 54 36 81]
 [40 40 90 54]
 [20 56 12 12]]

Частка матриць
[[0.66666667 2.33333333 0.5        0.57142857]
 [0.875      1.5        0.44444444 1.        ]
 [1.6        0.4        0.9        0.66666667]
 [5.         0.875      0.75       0.33333333]]


Висновок: Протягом лабораторної роботи ми ознайомились з можливостями бібліотеки Numpy і навчились за її допомогою створювати та взаємодіяти з матрицями, векторами.